/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_oboesample_MainActivity */

#ifndef _Included_com_example_oboesample_MainActivity
#define _Included_com_example_oboesample_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_oboesample_MainActivity
 * Method:    native_playUriAudio
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_oboesample_MainActivity_native_1playUriAudio
  (JNIEnv *, jobject, jstring);

JNIEXPORT void JNICALL
Java_com_example_oboesample_MainActivity_native_1playAssetAudio(JNIEnv *, jobject, jobject, jstring);

JNIEXPORT void JNICALL
Java_com_example_oboesample_MainActivity_native_1recordPcm(JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
